CC = gcc
CFLAGS = -Wall -ggdb

run_test:
	$(CC) $(CFLAGS) main.c -o main
	./main

clean:
	rm -rf main

help:
	@echo "To compile and run test: make run_test"
	@echo "To clean all not necessary files: make clean"